version: "2"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ewp
      - MYSQL_USER=ewpuser
      - MYSQL_PASSWORD=ewppassword
      - MYSQL_ROOT_PASSWORD=ewppassword
    networks:
      - inner
    ports:
      - "3306:3306"

  web:
    depends_on:
      - db
    build: local-ewp
    volumes:
      - ./local-ewp/ewp-data:/root:ro
    networks:
      inner:
      outer:
        aliases:
          - local.ewp.uma.es

  registry:
    image: docker.pkg.github.com/erasmus-without-paper/ewp-registry-service/ewp-registry-service:latest
    entrypoint: /root/entrypoint_register_keys.sh
    volumes:
      - ./local-registry/registry_data:/root
    networks:
      outer:
        aliases:
          - local.dev-registry.erasmuswithoutpaper.eu

  proxy:
    build: proxy
    networks:
      - outer
    ports:
      - "1328:80"

networks:
  inner:
  outer:
